version: "2"

linters:
  default: standard
  enable:
    - gosec
    - bodyclose
    - noctx
    - gocritic
    - revive
    - unparam
    - misspell
    - prealloc
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - hugeParam
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: exported
          disabled: true
        - name: increment-decrement
        - name: var-naming
          disabled: true
        - name: package-comments
          disabled: true
    gosec:
      excludes:
        - G104
    staticcheck:
      checks:
        - all
        - -SA1019
        - -ST1000
        - -ST1003
        - -ST1020
        - -ST1021
        - -ST1022

  exclusions:
    paths:
      - ".*\\.pb\\.go$"
      - ".*_gen\\.go$"
      - zz_generated.deepcopy.go
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
          - gocritic

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
